-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 15:21:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empaques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empaques` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empaques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tamaño`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tamaño` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tamaño` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`colores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `sku` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `activo` TINYINT(1) NULL,
  `empaques_id` INT NULL DEFAULT 0,
  `tamaño_id` INT NULL DEFAULT 0,
  `colores_id` INT NULL DEFAULT 0,
  `categorias_id` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_flores_Empaques1_idx` (`empaques_id` ASC),
  INDEX `fk_flores_tamaño1_idx` (`tamaño_id` ASC),
  INDEX `fk_flores_Colores1_idx` (`colores_id` ASC),
  INDEX `fk_flores_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_flores_Empaques1`
    FOREIGN KEY (`empaques_id`)
    REFERENCES `mydb`.`empaques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flores_tamaño1`
    FOREIGN KEY (`tamaño_id`)
    REFERENCES `mydb`.`tamaño` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flores_Colores1`
    FOREIGN KEY (`colores_id`)
    REFERENCES `mydb`.`colores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flores_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`etiquetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`etiquetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`caracteristicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`caracteristicas` (
  `id` INT NOT NULL,
  `caracteristica` VARCHAR(45) NULL,
  `flores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Caracteristicas_flores_idx` (`flores_id` ASC),
  CONSTRAINT `fk_Caracteristicas_flores`
    FOREIGN KEY (`flores_id`)
    REFERENCES `mydb`.`flores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flores_etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flores_etiquetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flores_etiquetas` (
  `flores_id` INT NOT NULL,
  `etiquetas_id` INT NOT NULL,
  PRIMARY KEY (`flores_id`, `etiquetas_id`),
  INDEX `fk_flores_has_etiquetas_etiquetas1_idx` (`etiquetas_id` ASC),
  INDEX `fk_flores_has_etiquetas_flores1_idx` (`flores_id` ASC),
  CONSTRAINT `fk_flores_has_etiquetas_flores1`
    FOREIGN KEY (`flores_id`)
    REFERENCES `mydb`.`flores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flores_has_etiquetas_etiquetas1`
    FOREIGN KEY (`etiquetas_id`)
    REFERENCES `mydb`.`etiquetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anio` VARCHAR(45) NULL,
  `mes` VARCHAR(45) NULL,
  `dia` VARCHAR(45) NULL,
  `flores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_flores1_idx` (`flores_id` ASC),
  CONSTRAINT `fk_agenda_flores1`
    FOREIGN KEY (`flores_id`)
    REFERENCES `mydb`.`flores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imagen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(45) NULL,
  `file_type` VARCHAR(45) NULL,
  `tamaño_id` INT NOT NULL,
  `colores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_tamaño1_idx` (`tamaño_id` ASC),
  INDEX `fk_imagen_colores1_idx` (`colores_id` ASC),
  CONSTRAINT `fk_imagen_tamaño1`
    FOREIGN KEY (`tamaño_id`)
    REFERENCES `mydb`.`tamaño` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagen_colores1`
    FOREIGN KEY (`colores_id`)
    REFERENCES `mydb`.`colores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flores_has_imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flores_has_imagen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flores_has_imagen` (
  `flores_id` INT NOT NULL,
  `imagen_id` INT NOT NULL,
  PRIMARY KEY (`flores_id`, `imagen_id`),
  INDEX `fk_flores_has_imagen_imagen1_idx` (`imagen_id` ASC),
  INDEX `fk_flores_has_imagen_flores1_idx` (`flores_id` ASC),
  CONSTRAINT `fk_flores_has_imagen_flores1`
    FOREIGN KEY (`flores_id`)
    REFERENCES `mydb`.`flores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flores_has_imagen_imagen1`
    FOREIGN KEY (`imagen_id`)
    REFERENCES `mydb`.`imagen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `flores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pago_flores1_idx` (`flores_id` ASC),
  CONSTRAINT `fk_pago_flores1`
    FOREIGN KEY (`flores_id`)
    REFERENCES `mydb`.`flores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
